"""The inference backend interface and its capability contract.

Everything above this line in the architecture (Ego, Id, neuocytes, supervisor)
talks only to this interface. A backend advertises what it can actually do; the
harness never assumes a capability that was not measured.

Capability flag vocabulary, deliberately fine-grained because these are NOT
equivalent and conflating them is the failure mode this project exists to
avoid:

``weight_ownership``
    ``single_resident_set`` -- one loaded copy of the weights serves every
    session. ``per_process`` -- each process loaded its own copy.
``kv_mode``
    ``shared_prefix`` -- a forked prefix physically shares KV cells with its
    source. ``copied_prefix`` -- a fork duplicates the KV bytes.
    ``recomputed`` -- there is no cache transfer at all; a prefix is rebuilt by
    re-evaluating its exact tokens. ``simulated`` -- not real inference.
``concurrency_mode``
    ``serialized`` -- requests queue behind one another. ``batched`` -- several
    sequences advance inside a single fused kernel launch (continuous
    batching). ``overlapped`` -- independent kernels from distinct sessions
    genuinely execute simultaneously on the device.
``physical_overlap_verified``
    Only true with GPU-timeline evidence. Asynchronous Python calls, several
    OS processes, batching and raw throughput are NOT evidence.
``prefix_reuse_verified``
    Only true once a forked prefix has been compared against an exact
    recomputation and matched.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, Sequence, runtime_checkable


@dataclass(slots=True)
class Capabilities:
    backend_kind: str
    is_simulated: bool
    device: str = "cpu"
    device_names: list[str] = field(default_factory=list)
    weight_ownership: str = "single_resident_set"
    kv_mode: str = "recomputed"
    concurrency_mode: str = "serialized"
    continuous_batching: bool = False
    physical_overlap_verified: bool = False
    prefix_reuse_verified: bool = False
    max_sessions: int = 1
    model_generation: str = ""
    tool_calling: str = "harness_validated"
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {k: getattr(self, k) for k in self.__slots__}


@runtime_checkable
class InferenceBackend(Protocol):
    """Minimum surface every backend must provide."""

    backend_kind: str
    is_simulated: bool

    def load(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
    def capabilities(self) -> dict[str, Any]: ...

    def tokenize(self, text: str, *, add_special: bool = False,
                 parse_special: bool = True) -> list[int]: ...
    def detokenize(self, tokens: Sequence[int], *, special: bool = False) -> str: ...
    def apply_chat_template(self, messages: Sequence[dict[str, str]], *,
                            add_assistant: bool = True) -> str: ...

    def open_session(self, *, role: str, session_id: str | None = None,
                     seq_id: int | None = None) -> Any: ...
    def close_session(self, session_id: str, *, keep_prefix: bool = False) -> None: ...
    def ingest(self, session_id: str, tokens: Sequence[int], *,
               compute_logits: bool = True) -> int: ...
    def generate(self, session_id: str, **kwargs: Any) -> Any: ...

    def fork_prefix(self, *, src_session_id: str, prefix_len: int, role: str,
                    session_id: str | None = None,
                    snapshot_id: str | None = None) -> Any: ...
    def restore_prefix(self, *, session_id: str, tokens: Sequence[int],
                       snapshot_id: str | None = None) -> int: ...


SIMULATED_BANNER = (
    "SIMULATED BACKEND -- deterministic stub output, NOT model inference. "
    "Any text below was generated by a hash function, not by a language model."
)
